theme: 0
proxyOrder: 2
connProxy: 0
connMode: true
connProfile: true
selectAfterUpdated: true
mixinType: 1
bypassText: "# 系统代理跳过列表 起作用的

  bypass:
  \  - \"localhost\"

  \  - 127.*

  \  - 10.*

  \  - 172.16.*

  \  - 172.17.*

  \  - 172.18.*

  \  - 172.19.*

  \  - 172.20.*

  \  - 172.21.*

  \  - 172.22.*

  \  - 172.23.*

  \  - 172.24.*

  \  - 172.25.*

  \  - 172.26.*

  \  - 172.27.*

  \  - 172.28.*

  \  - 172.29.*

  \  - 172.30.*

  \  - 172.31.*

  \  - 192.168.*

  \  - <local>


  \ "
childProcessText: >
  processes: # array
    # 启动订阅转换程序，端口号7893
    - command: "subconverter.exe" # run.cmd 程序名称 subconverter.exe -cfw >>logs/run.log 2>&1
      args:
        - "-cfw" # 运行参数1
      options:
        cwd: subconverter # 子进程工作目录
        #detached: true # 子进程独立于其父进程运行
        #shell: true # 则在 shell 中运行 command
        windowsHide: true # 隐藏子进程的控制台窗口
    # 启动网易云，端口号16375
    - command: "unblockneteasemusic.exe" # 启动网易云
      args:
        - "-p" # 运行参数1
        - "16375" # 运行参数2
      options:
        cwd: unblockNeteaseMusic # 子进程工作目录
        #detached: true # 子进程独立于其父进程运行
        #shell: true # 则在 shell 中运行 command
        windowsHide: true # 隐藏子进程的控制台窗口
